### ISSUE TITLE
Git requirement workaround

### ISSUE THREAD

**Issue by polachz** [ocroz/wsl2-boot#4]
Hi.

maybe this commad will work and helps to elliminate tee command from Windows Git suite. 

try this and let me know if it works for you:

`powershell.exe -command "& { powershell.exe -ExecutionPolicy Bypass -file .\wsl-boot.ps1 2>&1 | tee c:\boot.log}"`

It uses native PowerShell tee scriptlet. On my computer it fills the log with status and error messages correctly.

Best Regards

Zdenek

**Comment by ocroz** [comment]
Great, thank you for the workaround. I'll update the code with this better approach.

**Comment by ocroz** [comment]
Code updated : [Replace GitBash tee by PowerShell tee](https://github.com/ocroz/wsl2-boot/commit/a59083935a60633bb86caecf0e7d51429f825528).
